engine = "Llvm"
out = ["Lcov", "Json", "Html"]
output-dir = "coverage"
run-types = ["Tests", "Lib"]
exclude-files = ["target/*"]
timeout = "300"
all = true
branch = true
fail-under = 95.0
force-clean = true
